/*
 Navicat Premium Data Transfer

 Source Server         : local
 Source Server Type    : MySQL
 Source Server Version : 80039
 Source Host           : localhost:3306
 Source Schema         : veda_source

 Target Server Type    : MySQL
 Target Server Version : 80039
 File Encoding         : 65001

 Date: 16/08/2024 23:34:05
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for stored_event
-- ----------------------------
DROP TABLE IF EXISTS `stored_event`;
CREATE TABLE `stored_event`  (
  `id` bigint(0) NOT NULL AUTO_INCREMENT,
  `event_body` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `occurred_on` datetime(6) NULL DEFAULT NULL,
  `type_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `user_id` bigint(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `FK4y0r4thyym073n8jo5a5pci88`(`user_id`) USING BTREE,
  CONSTRAINT `FK4y0r4thyym073n8jo5a5pci88` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 19 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of stored_event
-- ----------------------------
INSERT INTO `stored_event` VALUES (1, '{\"userinfo\":{\"token\":\"41e437beb84d4affa6090421914b8a6f\",\"userId\":1,\"username\":\"admin\",\"avatar\":\"avatar.jpg\",\"credential\":{\"identifier\":\"admin\",\"type\":\"PASSWORD\"},\"permissions\":[\"user:view\",\"organization:delete\",\"user:delete\",\"role:update\",\"log:view\",\"resource:create\",\"resource:delete\",\"resource:view\",\"user:update\",\"storage:delete\",\"sys\",\"storage:view\",\"organization:create\",\"log:clean\",\"user:create\",\"storage:update\",\"role:create\",\"storage:markAsDefault\",\"role:view\",\"role:delete\",\"storage:create\",\"resource:update\",\"organization:update\",\"dashboard\"]},\"ip\":\"0:0:0:0:0:0:0:1\"}', '2024-08-06 19:16:08.381916', 'tech.veda.cms.sys.event.UserLoggedIn', 1);
INSERT INTO `stored_event` VALUES (2, '{\"userinfo\":{\"token\":\"8f073f46f2b346538b379cec4853ce14\",\"userId\":1,\"username\":\"admin\",\"avatar\":\"avatar.jpg\",\"credential\":{\"identifier\":\"admin\",\"type\":\"PASSWORD\"},\"permissions\":[\"user:view\",\"organization:delete\",\"user:delete\",\"role:update\",\"log:view\",\"resource:create\",\"resource:delete\",\"resource:view\",\"user:update\",\"storage:delete\",\"sys\",\"storage:view\",\"organization:create\",\"log:clean\",\"user:create\",\"storage:update\",\"role:create\",\"storage:markAsDefault\",\"role:view\",\"role:delete\",\"storage:create\",\"resource:update\",\"organization:update\",\"dashboard\"]},\"ip\":\"0:0:0:0:0:0:0:1\"}', '2024-08-06 19:19:32.409328', 'tech.veda.cms.sys.event.UserLoggedIn', 1);
INSERT INTO `stored_event` VALUES (3, '{\"userinfo\":{\"token\":\"a7ae252f5fc84b17a858c3390b06f4c3\",\"userId\":1,\"username\":\"admin\",\"avatar\":\"avatar.jpg\",\"credential\":{\"identifier\":\"admin\",\"type\":\"PASSWORD\"},\"permissions\":[\"user:view\",\"organization:delete\",\"user:delete\",\"role:update\",\"log:view\",\"resource:create\",\"resource:delete\",\"resource:view\",\"user:update\",\"storage:delete\",\"sys\",\"storage:view\",\"organization:create\",\"log:clean\",\"user:create\",\"storage:update\",\"role:create\",\"storage:markAsDefault\",\"role:view\",\"role:delete\",\"storage:create\",\"resource:update\",\"organization:update\",\"dashboard\"]},\"ip\":\"0:0:0:0:0:0:0:1\"}', '2024-08-06 19:23:00.909013', 'tech.veda.cms.sys.event.UserLoggedIn', 1);
INSERT INTO `stored_event` VALUES (4, '{\"userinfo\":{\"token\":\"62ee3ca13e2c472b825f64aa27c7381f\",\"userId\":1,\"username\":\"admin\",\"avatar\":\"avatar.jpg\",\"credential\":{\"identifier\":\"admin\",\"type\":\"PASSWORD\"},\"permissions\":[\"user:view\",\"organization:delete\",\"user:delete\",\"role:update\",\"log:view\",\"resource:create\",\"resource:delete\",\"resource:view\",\"user:update\",\"storage:delete\",\"sys\",\"storage:view\",\"organization:create\",\"log:clean\",\"user:create\",\"storage:update\",\"role:create\",\"storage:markAsDefault\",\"role:view\",\"role:delete\",\"storage:create\",\"resource:update\",\"organization:update\",\"dashboard\"]},\"ip\":\"0:0:0:0:0:0:0:1\"}', '2024-08-06 19:25:11.611110', 'tech.veda.cms.sys.event.UserLoggedIn', 1);
INSERT INTO `stored_event` VALUES (5, '{\"userinfo\":{\"token\":\"1a160f9163954663975c993cf670ec1e\",\"userId\":1,\"username\":\"admin\",\"avatar\":\"avatar.jpg\",\"credential\":{\"identifier\":\"admin\",\"type\":\"PASSWORD\"},\"permissions\":[\"user:view\",\"organization:delete\",\"user:delete\",\"role:update\",\"log:view\",\"resource:create\",\"resource:delete\",\"resource:view\",\"user:update\",\"storage:delete\",\"sys\",\"storage:view\",\"organization:create\",\"log:clean\",\"user:create\",\"storage:update\",\"role:create\",\"storage:markAsDefault\",\"role:view\",\"role:delete\",\"storage:create\",\"resource:update\",\"organization:update\",\"dashboard\"]},\"ip\":\"0:0:0:0:0:0:0:1\"}', '2024-08-06 20:37:31.350780', 'tech.veda.cms.sys.event.UserLoggedIn', 1);
INSERT INTO `stored_event` VALUES (6, '{\"userinfo\":{\"token\":\"7f254bc118df44c29157c5410cdc41ef\",\"userId\":1,\"username\":\"admin\",\"avatar\":\"avatar.jpg\",\"credential\":{\"identifier\":\"admin\",\"type\":\"PASSWORD\"},\"permissions\":[\"user:view\",\"organization:delete\",\"user:delete\",\"role:update\",\"log:view\",\"resource:create\",\"resource:delete\",\"resource:view\",\"user:update\",\"storage:delete\",\"sys\",\"storage:view\",\"organization:create\",\"log:clean\",\"user:create\",\"storage:update\",\"role:create\",\"storage:markAsDefault\",\"role:view\",\"role:delete\",\"storage:create\",\"resource:update\",\"organization:update\",\"dashboard\"]},\"ip\":\"0:0:0:0:0:0:0:1\"}', '2024-08-06 20:38:59.904945', 'tech.veda.cms.sys.event.UserLoggedIn', 1);
INSERT INTO `stored_event` VALUES (7, '{\"userinfo\":{\"token\":\"3968406877424d46a434ed097b57f6e8\",\"userId\":1,\"username\":\"admin\",\"avatar\":\"avatar.jpg\",\"credential\":{\"identifier\":\"admin\",\"type\":\"PASSWORD\"},\"permissions\":[\"user:view\",\"organization:delete\",\"user:delete\",\"role:update\",\"log:view\",\"resource:create\",\"resource:delete\",\"resource:view\",\"user:update\",\"storage:delete\",\"sys\",\"storage:view\",\"organization:create\",\"log:clean\",\"user:create\",\"storage:update\",\"role:create\",\"storage:markAsDefault\",\"role:view\",\"role:delete\",\"storage:create\",\"resource:update\",\"organization:update\",\"dashboard\"]},\"ip\":\"0:0:0:0:0:0:0:1\"}', '2024-08-06 20:40:17.175869', 'tech.veda.cms.sys.event.UserLoggedIn', 1);
INSERT INTO `stored_event` VALUES (8, '{\"userinfo\":{\"token\":\"21ddc85fbb0d4fe59a22fa74a45e87c2\",\"userId\":1,\"username\":\"admin\",\"avatar\":\"avatar.jpg\",\"credential\":{\"identifier\":\"admin\",\"type\":\"PASSWORD\"},\"permissions\":[\"user:view\",\"organization:delete\",\"user:delete\",\"role:update\",\"log:view\",\"resource:create\",\"resource:delete\",\"resource:view\",\"user:update\",\"storage:delete\",\"sys\",\"storage:view\",\"organization:create\",\"log:clean\",\"user:create\",\"storage:update\",\"role:create\",\"storage:markAsDefault\",\"role:view\",\"role:delete\",\"storage:create\",\"resource:update\",\"organization:update\",\"dashboard\"]},\"ip\":\"0:0:0:0:0:0:0:1\"}', '2024-08-06 20:42:40.822539', 'tech.veda.cms.sys.event.UserLoggedIn', 1);
INSERT INTO `stored_event` VALUES (9, '{\"userinfo\":{\"token\":\"c28c7243460146919d3cf153da9e471d\",\"userId\":1,\"username\":\"admin\",\"avatar\":\"avatar.jpg\",\"credential\":{\"identifier\":\"admin\",\"type\":\"PASSWORD\"},\"permissions\":[\"user:view\",\"organization:delete\",\"user:delete\",\"role:update\",\"log:view\",\"resource:create\",\"resource:delete\",\"resource:view\",\"user:update\",\"storage:delete\",\"sys\",\"storage:view\",\"organization:create\",\"log:clean\",\"user:create\",\"storage:update\",\"role:create\",\"storage:markAsDefault\",\"role:view\",\"role:delete\",\"storage:create\",\"resource:update\",\"organization:update\",\"dashboard\"]},\"ip\":\"0:0:0:0:0:0:0:1\"}', '2024-08-06 20:45:19.457930', 'tech.veda.cms.sys.event.UserLoggedIn', 1);
INSERT INTO `stored_event` VALUES (10, '{\"userinfo\":{\"token\":\"ee13089e4a854a0ba4637655a52619aa\",\"userId\":1,\"username\":\"admin\",\"avatar\":\"avatar.jpg\",\"credential\":{\"identifier\":\"admin\",\"type\":\"PASSWORD\"},\"permissions\":[\"user:view\",\"organization:delete\",\"user:delete\",\"role:update\",\"log:view\",\"resource:create\",\"resource:delete\",\"resource:view\",\"user:update\",\"storage:delete\",\"sys\",\"storage:view\",\"organization:create\",\"log:clean\",\"user:create\",\"storage:update\",\"role:create\",\"storage:markAsDefault\",\"role:view\",\"role:delete\",\"storage:create\",\"resource:update\",\"organization:update\",\"dashboard\"]},\"ip\":\"0:0:0:0:0:0:0:1\"}', '2024-08-06 20:47:12.888286', 'tech.veda.cms.sys.event.UserLoggedIn', 1);
INSERT INTO `stored_event` VALUES (11, '{\"userinfo\":{\"token\":\"70d4d06512544b418b114f4904f31ba8\",\"userId\":1,\"username\":\"admin\",\"avatar\":\"avatar.jpg\",\"credential\":{\"identifier\":\"admin\",\"type\":\"PASSWORD\"},\"permissions\":[\"user:view\",\"organization:delete\",\"user:delete\",\"role:update\",\"log:view\",\"resource:create\",\"resource:delete\",\"resource:view\",\"user:update\",\"storage:delete\",\"sys\",\"storage:view\",\"organization:create\",\"log:clean\",\"user:create\",\"storage:update\",\"role:create\",\"storage:markAsDefault\",\"role:view\",\"role:delete\",\"storage:create\",\"resource:update\",\"organization:update\",\"dashboard\"]},\"ip\":\"0:0:0:0:0:0:0:1\"}', '2024-08-06 20:56:45.526075', 'tech.veda.cms.sys.event.UserLoggedIn', 1);
INSERT INTO `stored_event` VALUES (12, '{\"userinfo\":{\"token\":\"8c7baef5d6c64615bc5122d3bf644bec\",\"userId\":1,\"username\":\"admin\",\"avatar\":\"avatar.jpg\",\"credential\":{\"identifier\":\"admin\",\"type\":\"PASSWORD\"},\"permissions\":[\"user:view\",\"organization:delete\",\"user:delete\",\"role:update\",\"log:view\",\"resource:create\",\"resource:delete\",\"resource:view\",\"user:update\",\"storage:delete\",\"sys\",\"storage:view\",\"organization:create\",\"log:clean\",\"user:create\",\"storage:update\",\"role:create\",\"storage:markAsDefault\",\"role:view\",\"role:delete\",\"storage:create\",\"resource:update\",\"organization:update\",\"dashboard\"]},\"ip\":\"0:0:0:0:0:0:0:1\"}', '2024-08-06 22:25:58.990472', 'tech.veda.cms.sys.event.UserLoggedIn', 1);
INSERT INTO `stored_event` VALUES (13, '{\"userinfo\":{\"token\":\"d318f803ed8949df9d09aa03c7e8b015\",\"userId\":1,\"username\":\"admin\",\"avatar\":\"avatar.jpg\",\"credential\":{\"identifier\":\"admin\",\"type\":\"PASSWORD\"},\"permissions\":[\"user:view\",\"organization:delete\",\"user:delete\",\"role:update\",\"log:view\",\"resource:create\",\"resource:delete\",\"resource:view\",\"user:update\",\"storage:delete\",\"sys\",\"storage:view\",\"organization:create\",\"log:clean\",\"user:create\",\"storage:update\",\"role:create\",\"storage:markAsDefault\",\"role:view\",\"role:delete\",\"storage:create\",\"resource:update\",\"organization:update\",\"dashboard\"]},\"ip\":\"0:0:0:0:0:0:0:1\"}', '2024-08-06 22:27:24.580283', 'tech.veda.cms.sys.event.UserLoggedIn', 1);
INSERT INTO `stored_event` VALUES (14, '{\"userinfo\":{\"token\":\"7ecb07d8facf4385b4df72baef9a86d3\",\"userId\":1,\"username\":\"admin\",\"avatar\":\"avatar.jpg\",\"credential\":{\"identifier\":\"admin\",\"type\":\"PASSWORD\"},\"permissions\":[\"user:view\",\"organization:delete\",\"user:delete\",\"role:update\",\"log:view\",\"resource:create\",\"resource:delete\",\"resource:view\",\"user:update\",\"storage:delete\",\"sys\",\"storage:view\",\"organization:create\",\"log:clean\",\"user:create\",\"storage:update\",\"role:create\",\"storage:markAsDefault\",\"role:view\",\"role:delete\",\"storage:create\",\"resource:update\",\"organization:update\",\"dashboard\"]},\"ip\":\"0:0:0:0:0:0:0:1\"}', '2024-08-06 22:30:21.703653', 'tech.veda.cms.sys.event.UserLoggedIn', 1);
INSERT INTO `stored_event` VALUES (15, '{\"userinfo\":{\"token\":\"ba04eb1e46014c669f79ec2f8981b6b6\",\"userId\":1,\"username\":\"admin\",\"avatar\":\"avatar.jpg\",\"credential\":{\"identifier\":\"admin\",\"type\":\"PASSWORD\"},\"permissions\":[\"user:view\",\"organization:delete\",\"user:delete\",\"role:update\",\"log:view\",\"resource:create\",\"resource:delete\",\"resource:view\",\"user:update\",\"storage:delete\",\"sys\",\"storage:view\",\"organization:create\",\"log:clean\",\"user:create\",\"storage:update\",\"role:create\",\"storage:markAsDefault\",\"role:view\",\"role:delete\",\"storage:create\",\"resource:update\",\"organization:update\",\"dashboard\"]},\"ip\":\"0:0:0:0:0:0:0:1\"}', '2024-08-06 22:31:31.494991', 'tech.veda.cms.sys.event.UserLoggedIn', 1);
INSERT INTO `stored_event` VALUES (16, '{\"userinfo\":{\"token\":\"473c7e4d76384cf783744a493a8bf235\",\"userId\":1,\"username\":\"admin\",\"avatar\":\"avatar.jpg\",\"credential\":{\"identifier\":\"admin\",\"type\":\"PASSWORD\"},\"permissions\":[\"user:view\",\"organization:delete\",\"user:delete\",\"role:update\",\"log:view\",\"resource:create\",\"resource:delete\",\"resource:view\",\"user:update\",\"storage:delete\",\"sys\",\"storage:view\",\"organization:create\",\"log:clean\",\"user:create\",\"storage:update\",\"role:create\",\"storage:markAsDefault\",\"role:view\",\"role:delete\",\"storage:create\",\"resource:update\",\"organization:update\",\"dashboard\"]},\"ip\":\"0:0:0:0:0:0:0:1\"}', '2024-08-06 22:34:27.194358', 'tech.veda.cms.sys.event.UserLoggedIn', 1);
INSERT INTO `stored_event` VALUES (17, '{\"userinfo\":{\"token\":\"3a593ca968884bedafad7e97a9bf77c9\",\"userId\":1,\"username\":\"admin\",\"avatar\":\"avatar.jpg\",\"credential\":{\"identifier\":\"admin\",\"type\":\"PASSWORD\"},\"permissions\":[\"user:view\",\"organization:delete\",\"user:delete\",\"role:update\",\"log:view\",\"resource:create\",\"resource:delete\",\"resource:view\",\"user:update\",\"storage:delete\",\"sys\",\"storage:view\",\"organization:create\",\"log:clean\",\"user:create\",\"storage:update\",\"role:create\",\"storage:markAsDefault\",\"role:view\",\"role:delete\",\"storage:create\",\"resource:update\",\"organization:update\",\"dashboard\"]},\"ip\":\"0:0:0:0:0:0:0:1\"}', '2024-08-15 10:30:26.956562', 'tech.veda.cms.sys.event.UserLoggedIn', 1);
INSERT INTO `stored_event` VALUES (18, '{\"userinfo\":{\"token\":\"fed097a1709e4219b918e2cad184f7fe\",\"userId\":1,\"username\":\"admin\",\"avatar\":\"avatar.jpg\",\"credential\":{\"identifier\":\"admin\",\"type\":\"PASSWORD\"},\"permissions\":[\"user:view\",\"organization:delete\",\"user:delete\",\"role:update\",\"log:view\",\"resource:create\",\"resource:delete\",\"resource:view\",\"user:update\",\"storage:delete\",\"sys\",\"storage:view\",\"organization:create\",\"log:clean\",\"user:create\",\"storage:update\",\"role:create\",\"storage:markAsDefault\",\"role:view\",\"role:delete\",\"storage:create\",\"resource:update\",\"organization:update\",\"dashboard\"]},\"ip\":\"0:0:0:0:0:0:0:1\"}', '2024-08-16 19:08:56.915680', 'tech.veda.cms.sys.event.UserLoggedIn', 1);

SET FOREIGN_KEY_CHECKS = 1;
