spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.auto_quote_keyword: true
#  thymeleaf:
#    template-resolver-order: 1
#    suffix: .ftl
  application:
    name: veda-source



  datasource:
    druid:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/veda_source?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      encoding: utf8
      data-locations: classpath:data.sql
      mode: always
      continue-on-error: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  profiles:
    include: biz
server:
  servlet:
    context-path: /veda-source

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: status  # 全局逻辑删除的字段名
      logic-delete-value: 0        # 逻辑已删除值（例如：1表示已删除）
      logic-not-delete-value: 1

email:
  from: 404888541@qq.com
#  to: 404888541@qq.com
  to: xinyu@miclglobal.com
  host: smtp.qq.com
  auth: oalbkmllrknjcaif
  port: 587
  subject: Client Contact
